version: '3'

networks:
  posttest-network:

services:
  app:
    container_name: posttest-app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - posttest-network
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/lottery
      DATASOURCE_USER: user
      DATASOURCE_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8888:8888"
  db:
    container_name: postgres
    image: postgres:16.0
    environment:
      POSTGRES_DB: lottery
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - posttest-network

volumes:
  db: