name: Automate Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    needs:
      - linter
    steps:
      -   name: Checkout Code
          uses: actions/checkout@v3
      -   name: Setup Java17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu'
      -   name: Run Unit Tests
          run: ./gradlew test
  build:
    name: Build Java
    runs-on: ubuntu-latest
    needs:
      - unit-test
    steps:
      -   name: Checkout Code
          uses: actions/checkout@v3
      -   name: Setup Java17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu'
      -   name: Build Java
          run: ./gradlew build